import { Items, partialItems } from "./itemNames";

const assemblerSpeeds = {
    constructer: 0.5,
    assembler: 0.75,
    manufacturer: 1.0,
    "chemical-plant": 1.0,
    "gas-extractor": 1.0,
    "smelter-mk1": 0.5,
    "smelter-mk2": 1,
    "oil-pump": 1.0,
    "miner-mk1": 0.75,
    "water-pump-mk1": 1,
    "water-filter": 1,
    greenhouse: 0.5,
    explorer: 2,
    prospector: 1,
    lumberjack: 4,
    "adamantium-drill": 1,
    "rock-crusher": 1,
    centrifuge: 1,
    "water-evaporator": 1,
    "lumberjack-school": 1,
    "wind-turbine": 5,
    "coal-power": 100,
    "nuclear-reactor": 2500,
    hydroponics: 5,
    "fire-wizard": 1.0,
    "necro-wizard": 1.0,
    "arcane-wizard": 1.0,
    "wizard-orb": 2.0,
    "bank": 1.0,
    "desktop-computer": 1,
} satisfies partialItems<number>;

export type Buildings = keyof typeof assemblerSpeeds;

const buildingPowerRequirementsPerSecond: partialItems<partialItems<number>> = {
    "adamantium-drill": { electricity: 100 },
    "chemical-plant": { electricity: 10 },
    "gas-extractor": { electricity: 15 },
    "lumberjack-school": { electricity: 5 },
    "miner-mk1": { electricity: 2 },
    "oil-pump": { electricity: 10 },
    "rock-crusher": { electricity: 20 },
    "smelter-mk1": { wood: 0.1 },
    "smelter-mk2": { wood: 0.1 },
    "water-evaporator": { electricity: 5 },
    "water-filter": { electricity: 5 },
    "water-pump-mk1": { electricity: 5 },
    assembler: { electricity: 6 },
    centrifuge: { electricity: 10 },
    constructer: { electricity: 1 },
    explorer: { electricity: 10 },
    greenhouse: { electricity: 1, fertilizer: 1, "clean-water": 1 },
    manufacturer: { electricity: 10 },
    prospector: { food: 0.05 },
    lumberjack: { food: 0.05 },
    "wind-turbine": {},
    "coal-power": { coal: 1 },
    "nuclear-reactor": { "nuclear-fuel": 0.1 },
    hydroponics: { electricity: 1, fertilizer: 1, "clean-water": 1 },
    "arcane-wizard": { "powerful-mana": 1 },
    "fire-wizard": { "powerful-mana": 1 },
    "necro-wizard": { "powerful-mana": 1 },
    "wizard-orb": { "powerful-mana": 1, },
    "bank": { "gold": 0.25 },
    "desktop-computer": { electricity: 1 },
} satisfies {
        [p in Buildings]: partialItems<number>;
    };

const buildingPowerDisplayWord: partialItems<string> = {
    prospector: "Food",
    lumberjack: "Food",
    "smelter-mk1": "Fuel",
    "smelter-mk2": "Fuel",
    "bank": "Gold",
} satisfies { [p in Buildings]?: string };

/**
 * A list of items that will double building efficiency for each item owned
 */
const buildingBoosts: { [p in Buildings]?: Items } = {
    constructer: "boost-constructor",
    lumberjack: "boost-lumberjack",
    "miner-mk1": "boost-miner-mk1",
    "chemical-plant": "boost-chemical-plant",
    "adamantium-drill": "boost-adamantium-drill",
    "gas-extractor": "boost-gas-extractor",
    "lumberjack-school": "boost-lumberjack-school",
    "oil-pump": "boost-oil-pump",
    "rock-crusher": "boost-rock-crusher",
    "smelter-mk1": "boost-smelter-mk1",
    "smelter-mk2": "boost-smelter-mk2",
    assembler: "boost-assembler",
    "water-pump-mk1": "boost-water-pump",
    centrifuge: "boost-centrifuge",
    explorer: "boost-explorer",
    greenhouse: "boost-greenhouse",
    manufacturer: "boost-manufacturer",
    "fire-wizard": "boost-wizard",
    "arcane-wizard": "boost-wizard",
    "necro-wizard": "boost-wizard",
    "wizard-orb": "boost-wizard",
    "bank": "boost-bank",
    "desktop-computer": "boost-desktop-computer",
};

// keys are the items that do the boosting, not the building.
const buildingBoostTiers: { [p in Items]?: number[] } = {

};

const defaultBuildingBoostTiers: number[] = [
    2 ** 0,
    2 ** 1,
    2 ** 2,
    2 ** 3,
    2 ** 4,
    2 ** 5,
    2 ** 6,
    2 ** 7,
    2 ** 8,
    2 ** 9,
    2 ** 10,
];

const requiredBuildings: {
    [p in Items]: (Buildings | "by-hand")[];
} = {
    youwin: ["manufacturer"],
    "research-the-end": ["by-hand"],
    begin: ["by-hand"],
    prospector: ["by-hand"],
    lumberjack: ["lumberjack-school"],
    "lumberjack-school": ["by-hand", "manufacturer"],
    "research-metal": ["by-hand"],
    "research-small-battery": ["by-hand"],
    "small-battery": ["by-hand", "constructer"],
    electricity: ["wind-turbine", "coal-power", "nuclear-reactor"],
    "wind-turbine": ["by-hand", "constructer"],
    food: ["by-hand", "prospector", "hydroponics"],

    "coal-power": ["by-hand", "manufacturer"],
    "nuclear-reactor": ["manufacturer"],

    money: ["by-hand", "bank"],
    "research-car": ["desktop-computer"],
    "research-marg": ["by-hand"],
    science6: ["by-hand"],

    "adamantium-drill": ["manufacturer"],
    "advanced-circuit": ["assembler"],
    "crushed-uranium": ["rock-crusher"],
    "nuclear-fuel": ["centrifuge"],
    "": [],
    "iron-frame": ["by-hand", "constructer"],
    "rock-crusher": ["by-hand", "assembler"],
    "research-adamantium-drill": ["by-hand"],
    "research-aluminum": ["by-hand"],
    "research-arbol": ["by-hand"],
    "research-assembler": ["by-hand"],
    "research-computer": ["by-hand"],
    "research-explorer": ["by-hand"],
    "research-manufacturer": ["by-hand"],
    "research-natural-gas": ["by-hand"],
    "research-nitrogen": ["by-hand"],
    "research-steel": ["by-hand"],
    "research-studonite": ["by-hand"],
    "research-uranium": ["by-hand"],
    "research-fluids": ["by-hand"],
    "research-wire": ["by-hand"],
    "research-oil": ["by-hand"],
    "research-advanced-circuitry": ["by-hand"],
    "research-box": ["by-hand"],
    "research-constructor": ["by-hand"],
    "research-miner-mk1": ["by-hand"],
    "research-frames": ["by-hand"],
    "research-mass-click": ["by-hand"],
    "research-basic-circuit": ["by-hand"],
    "research-woodcutting": ["by-hand"],
    "research-money": ["by-hand"],

    "boost-lumberjack": ["by-hand"],
    "boost-miner-mk1": ["by-hand"],
    "boost-chemical-plant": ["by-hand"],
    "boost-adamantium-drill": ["by-hand"],
    "boost-gas-extractor": ["by-hand"],
    "boost-lumberjack-school": ["by-hand"],
    "boost-oil-pump": ["by-hand"],
    "boost-rock-crusher": ["by-hand"],
    "boost-smelter-mk1": ["by-hand"],
    "boost-smelter-mk2": ["by-hand"],
    "boost-assembler": ["by-hand"],
    "boost-water-pump": ["by-hand"],
    "boost-centrifuge": ["by-hand"],
    "boost-explorer": ["by-hand"],
    "boost-greenhouse": ["by-hand"],
    "boost-manufacturer": ["by-hand"],
    "boost-constructor": ["by-hand"],
    "boost-bank": ["by-hand"],
    "boost-desktop-computer": ["by-hand"],

    "research-science-1": ["by-hand"],
    "research-science-2": ["by-hand"],
    "research-science-3": ["by-hand"],
    "research-science-4": ["by-hand"],
    "research-science-5": ["by-hand"],
    "research-science-6": ["by-hand"],

    "research-box2": ["by-hand"],
    "research-box3": ["by-hand"],
    "research-box4": ["by-hand"],
    "research-box5": ["by-hand"],

    "water-evaporator": ["assembler"],
    "evaporate-water": ["water-evaporator"],
    "gold-filament": ["assembler"],
    aluminum: ["smelter-mk2"],
    computer: ["manufacturer"],
    plastic: ["chemical-plant"],
    sand: ["miner-mk1"],
    science0: ["by-hand", "constructer"],
    science1: ["by-hand", "constructer"],
    science2: ["by-hand", "assembler"],
    science3: ["assembler"],
    science4: ["manufacturer"],
    science5: ["desktop-computer"],
    seed: ["by-hand"],
    u235: ["centrifuge"],
    centrifuge: ["manufacturer"],
    u234: [],
    slag: [],
    "bauxite-node": ["explorer"],
    "coal-node": ["explorer", "prospector"],
    "copper-node": ["explorer", "prospector"],
    "iron-node": ["explorer", "prospector"],
    "sandy-land": ["explorer", "prospector"],
    "stony-land": ["explorer", "prospector"],
    "wet-land": ["explorer", "prospector"],
    "gold-node": ["explorer"],
    "oil-node": ["explorer"],
    "studonite-node": ["explorer"],
    "uranium-node": ["explorer"],
    // raw
    gold: ["miner-mk1"],
    bauxite: ["adamantium-drill"],
    adamantium: ["chemical-plant"],
    gas: ["gas-extractor"],
    "iron-ore": ["miner-mk1", "by-hand"],
    "copper-ore": ["miner-mk1", "by-hand"],
    "uranium-ore": ["adamantium-drill"],
    water: ["water-pump-mk1"],
    oil: ["oil-pump"],
    coal: ["miner-mk1"],
    stone: ["miner-mk1", "by-hand"],
    studonite: ["miner-mk1"],
    // processed raw
    "iron-bar": ["smelter-mk1"],
    "copper-bar": ["smelter-mk1"],
    steel: ["smelter-mk2"],
    sulfur: ["chemical-plant"],
    glass: ["smelter-mk1"],
    "copper-wire": ["by-hand", "constructer"],
    "clean-water": ["water-filter"],
    tree: ["prospector", "greenhouse"],
    wood: ["lumberjack"],
    fertilizer: ["assembler"],
    nitrogen: ["gas-extractor"],
    // building materials
    gear: ["constructer", "by-hand"],
    pipe: ["constructer"],
    "adamantium-frame": ["assembler"],
    // advanced materials
    "sulfuric-acid": ["chemical-plant"],
    "basic-circuit": ["assembler"],
    solvent: ["chemical-plant"],
    // buildings
    "gas-extractor": ["assembler"],
    manufacturer: ["by-hand", "manufacturer"],
    assembler: ["by-hand", "assembler"],
    constructer: ["constructer", "by-hand"],
    "chemical-plant": ["assembler"],
    "miner-mk1": ["constructer"],
    "water-pump-mk1": ["constructer"],
    "oil-pump": ["assembler"],
    "smelter-mk1": ["by-hand", "constructer"],
    "smelter-mk2": ["constructer"],
    greenhouse: ["assembler"],
    hydroponics: ["manufacturer"],
    "water-filter": ["by-hand", "constructer"],

    explorer: ["assembler"],

    box: ["by-hand", "constructer"],
    "box-box": ["by-hand", "constructer"],
    box3: ["constructer"],
    box4: ["constructer"],
    box5: ["constructer"],
    tank: ["by-hand", "assembler"],

    "desk": ["by-hand"],
    "desktop-computer": ["by-hand"],
    "anti-grav-thruster": ["manufacturer"],
    "car-chassis": ["manufacturer"],
    "car-engine": ["manufacturer"],
    "crank-shaft": ["manufacturer"],
    "engine-block": ["manufacturer"],
    "engine-electronics": ["manufacturer"],
    "lime-juice": ["hydroponics"],
    "simple-syrup": ["hydroponics"],
    tequila: ["hydroponics"],
    "spark-plug": ["manufacturer"],
    "steering-wheel": ["manufacturer"],
    bank: ["by-hand"],
    car: ["by-hand", "manufacturer"],
    chair: ["manufacturer"],
    margarita: ["by-hand"],
    piston: ["manufacturer"],

    "telescope": ["by-hand"],

    "wizard-pop": ["necro-wizard", "fire-wizard", "arcane-wizard"],
    "raw-mana": ["by-hand", "wizard-orb"],
    "refined-mana": ["by-hand", "wizard-orb"],
    "powerful-mana": ["by-hand", "wizard-orb"],

    "arcane-wizard": ["by-hand", "wizard-orb"],
    "fire-wizard": ["by-hand", "wizard-orb"],
    "necro-wizard": ["by-hand", "wizard-orb"],

    "boost-wizard": ["by-hand"],
    "wizard-degree": ["by-hand", "wizard-orb"],
    "wizard-essence": ["by-hand", "wizard-orb"],
    "wizard-orb": ["by-hand"],
    "wizard-paragon": ["by-hand", "wizard-orb"],
    "wizard-power": [],

    'consume-arcane-wizard': ["by-hand", "wizard-orb"],
    'consume-fire-wizard': ["by-hand", "wizard-orb"],
    'consume-necro-wizard': ["by-hand", "wizard-orb"],
    'consume-wizard-pop': ["by-hand", "wizard-orb"],

    "research-wizard-tower": ["by-hand"],
};

export default {
    assemblerSpeeds,
    requiredBuildings,
    buildingPowerRequirementsPerSecond,
    buildingBoosts,
    buildingPowerDisplayWord,
    buildingBoostTiers,
    defaultBuildingBoostTiers,
};
