import { Items, partialItems } from "./itemNames";

const assemblerSpeeds = {
    constructer: 0.5,
    assembler: 0.75,
    manufacturer: 1.0,
    "chemical-plant": 1.0,
    "gas-extractor": 1.0,
    "smelter-mk1": 0.5,
    "smelter-mk2": 1,
    "oil-pump": 1.0,
    "miner-mk1": 0.75,
    "water-pump-mk1": 1,
    "water-pump-mk2": 5,
    "water-filter": 1,
    greenhouse: 0.5,
    hydroponics: 1.5,
    explorer: 2,
    prospector: 1,
    "adamantium-drill": 1,
    "rock-crusher": 1,
    centrifuge: 1,
    "water-evaporator": 1,
} satisfies partialItems<number>;

export type Buildings = keyof typeof assemblerSpeeds;

const requiredBuildings: {
    [p in Items]: (Buildings | "by-hand")[];
} = {
    begin: ["by-hand"],
    prospector: [],
    "adamantium-drill": ["manufacturer"],
    "advanced-circuit": ["assembler"],
    "crushed-uranium": ["rock-crusher"],
    "": [],
    "iron-frame": ["by-hand", "constructer"],
    "rock-crusher": ["by-hand", "assembler"],
    "research-adamantium-drill": ["by-hand"],
    "research-aluminum": ["by-hand"],
    "research-arbol": ["by-hand"],
    "research-assembler": ["by-hand"],
    "research-computer": ["by-hand"],
    "research-explorer": ["by-hand"],
    "research-manufacturer": ["by-hand"],
    "research-natural-gas": ["by-hand"],
    "research-nitrogen": ["by-hand"],
    "research-steel": ["by-hand"],
    "research-studonite": ["by-hand"],
    "research-uranium": ["by-hand"],
    "research-fluids": ["by-hand"],
    "research-wire": ["by-hand"],
    "research-oil": ["by-hand"],
    "research-advanced-circuitry": ["by-hand"],
    "research-box": ["by-hand"],
    "research-constructor": ["by-hand"],
    "research-miner-mk1": ["by-hand"],
    "research-frames": ["by-hand"],
    "research-mass-click": ["by-hand"],
    "research-basic-circuit": ["by-hand"],

    "research-science-1": ["by-hand"],
    "research-science-2": ["by-hand"],
    "research-science-3": ["by-hand"],
    "research-science-4": ["by-hand"],
    "research-science-5": ["by-hand"],

    "research-box2": ["by-hand"],
    "research-box3": ["by-hand"],
    "research-box4": ["by-hand"],
    "research-box5": ["by-hand"],

    "water-evaporator": ["by-hand", "assembler"],
    "evaporate-water": ["water-evaporator"],
    "gold-filament": ["assembler"],
    aluminum: ["smelter-mk2"],
    computer: ["manufacturer"],
    plastic: ["chemical-plant"],
    sand: ["miner-mk1"],
    science0: ["by-hand", "constructer"],
    science1: ["by-hand", "constructer", "assembler"],
    science2: ["by-hand", "assembler"],
    science3: ["by-hand", "assembler"],
    science4: ["by-hand", "assembler", "manufacturer"],
    science5: ["by-hand", "manufacturer"],
    seed: ["by-hand"],
    u235: ["centrifuge"],
    centrifuge: ["manufacturer"],
    u234: [],
    slag: [],

    land: ["explorer", "prospector"],
    "bauxite-node": ["explorer"],
    "coal-node": [],
    "copper-node": [],
    "gold-node": ["explorer"],
    "iron-node": [],
    "oil-node": ["explorer"],
    "sandy-land": [],
    "stony-land": [],
    "studonite-node": ["explorer"],
    "uranium-node": ["explorer"],
    "wet-land": [],
    // raw
    gold: ["miner-mk1"],
    bauxite: ["adamantium-drill"],
    adamantium: ["chemical-plant"],
    gas: ["gas-extractor"],
    "iron-ore": ["miner-mk1", "by-hand"],
    "copper-ore": ["miner-mk1", "by-hand"],
    "uranium-ore": ["adamantium-drill"],
    water: ["water-pump-mk1", "water-pump-mk2"],
    oil: ["oil-pump"],
    coal: ["miner-mk1", "by-hand"],
    stone: ["miner-mk1", "by-hand"],
    studonite: ["miner-mk1"],
    dust: [],
    // processed raw
    "iron-bar": ["smelter-mk1"],
    "copper-bar": ["smelter-mk1"],
    steel: ["smelter-mk2"],
    sulfur: ["chemical-plant"],
    glass: ["smelter-mk1"],
    "copper-wire": ["by-hand", "constructer"],
    "clean-water": ["water-filter"],
    tree: ["greenhouse", "hydroponics"],
    wood: ["constructer", "assembler", "manufacturer"],
    fertilizer: ["constructer", "assembler", "manufacturer"],
    nitrogen: ["gas-extractor"],
    // building materials
    gear: ["constructer", "by-hand"],
    pipe: ["by-hand", "constructer"],
    "adamantium-frame": ["by-hand", "assembler"],
    // advanced materials
    "sulfuric-acid": ["chemical-plant"],
    "basic-circuit": ["by-hand", "constructer", "assembler"],
    solvent: ["chemical-plant"],
    // buildings
    "gas-extractor": ["manufacturer", "assembler"],
    manufacturer: ["assembler", "manufacturer"],
    assembler: ["by-hand", "assembler", "manufacturer"],
    constructer: ["constructer", "by-hand"],
    "chemical-plant": ["assembler", "manufacturer"],
    "miner-mk1": ["by-hand", "constructer"],
    "water-pump-mk1": ["by-hand", "constructer", "assembler"],
    "water-pump-mk2": ["assembler", "manufacturer"],
    "oil-pump": ["assembler", "manufacturer"],
    "smelter-mk1": ["by-hand", "constructer", "assembler"],
    "smelter-mk2": ["by-hand", "assembler", "manufacturer"],
    greenhouse: ["constructer", "assembler", "by-hand"],
    hydroponics: ["manufacturer"],
    "water-filter": ["by-hand", "constructer", "assembler"],

    explorer: ["assembler"],

    box: ["by-hand", "constructer"],
    "box-box": ["by-hand", "constructer"],
    box3: ["constructer"],
    box4: ["constructer"],
    box5: ["constructer"],
    tank: ["by-hand", "assembler"],
};

export default {
    assemblerSpeeds,
    requiredBuildings,
};
