export type Items =
    | "begin"
    | "youwin"
    | "research-the-end"
    | "food"
    | "lumberjack"
    | "prospector"
    | "tree"
    | "wood"
    | "research-woodcutting"
    | "electricity"
    | "small-battery"
    | "research-small-battery"
    | "wind-turbine"
    | "lumberjack-school"
    | "adamantium"
    | "adamantium-drill"
    | "adamantium-frame"
    | "advanced-circuit"
    | "aluminum"
    | "assembler"
    | "basic-circuit"
    | "bauxite"
    | "box"
    | "box-box"
    | "box3"
    | "box4"
    | "box5"
    | "centrifuge"
    | "chemical-plant"
    | "clean-water"
    | "coal"
    | "computer"
    | "constructer"
    | "copper-bar"
    | "copper-ore"
    | "copper-wire"
    | "crushed-uranium"
    | "evaporate-water"
    | "explorer"
    | "fertilizer"
    | "gas"
    | "gas-extractor"
    | "gear"
    | "glass"
    | "gold"
    | "gold-filament"
    | "greenhouse"
    | "hydroponics"
    | "iron-bar"
    | "iron-frame"
    | "iron-ore"
    | "manufacturer"
    | "miner-mk1"
    | "nitrogen"
    | "oil"
    | "oil-pump"
    | "pipe"
    | "plastic"
    | "research-metal"
    | "research-adamantium-drill"
    | "research-advanced-circuitry"
    | "research-aluminum"
    | "research-arbol"
    | "research-assembler"
    | "research-basic-circuit"
    | "research-box"
    | "research-box2"
    | "research-box3"
    | "research-box4"
    | "research-box5"
    | "research-computer"
    | "research-constructor"
    | "research-fluids"
    | "research-frames"
    | "research-explorer"
    | "research-manufacturer"
    | "research-mass-click"
    | "research-miner-mk1"
    | "research-natural-gas"
    | "research-nitrogen"
    | "research-oil"
    | "research-science-1"
    | "research-science-2"
    | "research-science-3"
    | "research-science-4"
    | "research-science-5"
    | "research-steel"
    | "research-studonite"
    | "research-uranium"
    | "research-wire"
    | "research-money"
    | "coal-power"
    | "rock-crusher"
    | "sand"
    | "science0"
    | "science1"
    | "science2"
    | "science3"
    | "science4"
    | "science5"
    | "seed"
    | "slag"
    | "smelter-mk1"
    | "smelter-mk2"
    | "solvent"
    | "steel"
    | "stone"
    | "studonite"
    | "sulfur"
    | "sulfuric-acid"
    | "tank"
    | "u234"
    | "u235"
    | "uranium-ore"
    | "nuclear-fuel"
    | "water"
    | "water-evaporator"
    | "water-filter"
    | "water-pump-mk1"
    | "wet-land"
    | "sandy-land"
    | "copper-node"
    | "iron-node"
    | "coal-node"
    | "stony-land"
    | "oil-node"
    | "studonite-node"
    | "bauxite-node"
    | "uranium-node"
    | "gold-node"
    | "nuclear-reactor"
    | "money"
    | "boost-lumberjack"
    | "boost-miner-mk1"
    | "boost-chemical-plant"
    | "boost-adamantium-drill"
    | "boost-gas-extractor"
    | "boost-lumberjack-school"
    | "boost-oil-pump"
    | "boost-rock-crusher"
    | "boost-smelter-mk1"
    | "boost-smelter-mk2"
    | "boost-assembler"
    | "boost-water-pump"
    | "boost-centrifuge"
    | "boost-explorer"
    | "boost-greenhouse"
    | "boost-manufacturer"
    | "boost-constructor"

    // convert gold to money
    | "bank"

    // margaritas are required to win
    | "margarita"
    | "simple-syrup"
    | "lime-juice"
    | "tequila"

    // make some cars to win.
    // some ingredients are also required to make explorers
    | "car-engine"
    | "engine-block"
    | "engine-electronics"
    | "crank-shaft"
    | "spark-plug"
    | "piston"
    | "car"
    | "car-chassis"
    | "anti-grav-thruster"
    | "chair"
    | "steering-wheel"

    // the wizard's tower.
    // create wizard-paragon with 100 wizard degrees
    // research the wizard tower using a telescope
    // spend money to buy wizards
    // wizards make wizard-pop
    // create mana
    // each tier of mana requires 2 of the previous + mystical catalyst
    // create wizard degree with wizard power
    // consume things to make wizard power

    | "telescope"
    | "wizard-essence"
    | "raw-mana"
    | "refined-mana"
    | "powerful-mana"
    | "mystical-catalyst"
    | "wizard-orb"
    | "research-wizard-tower"
    | "wizard-paragon"
    | "arcane-wizard"
    | "fire-wizard"
    | "necro-wizard"
    | "wizard-pop"
    | "wizard-power"
    | "wizard-degree"
    | "consume-arcane-wizard"
    | "consume-fire-wizard"
    | "consume-necro-wizard"
    | "consume-wizard-pop"
    | "boost-wizard"
    | "";

export type itemsMap<T> = { [p in Items]: T };
export type partialItems<T> = Partial<itemsMap<T>>;
